/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CurchodButton {}
  interface CurchodButtonAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'CurchodButton': Components.CurchodButton;
  }

  interface StencilIntrinsicElements {
    'curchod-button': Components.CurchodButtonAttributes;
  }


  interface HTMLCurchodButtonElement extends Components.CurchodButton, HTMLStencilElement {}
  var HTMLCurchodButtonElement: {
    prototype: HTMLCurchodButtonElement;
    new (): HTMLCurchodButtonElement;
  };

  interface HTMLElementTagNameMap {
    'curchod-button': HTMLCurchodButtonElement
  }

  interface ElementTagNameMap {
    'curchod-button': HTMLCurchodButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
